### ISSUE TITLE
Festify won't work on proxied network

### ISSUE THREAD

**Issue by testr239** [Festify/app#120]
I am trying to use Festify on a network that is routed through its own proxy (university wifi).

I believe this is what is causing it not to work as it is unable to actually open the authorization page for Spotify. Some programs I use prompt me for a user and pass for the proxy, and others just work (I believe they use the automatic proxy settings from Internet Options)

It would be great if this could be fixed, or if someone knows a work around, please let me know!

Thanks

**Comment by NeoLegends** [comment]
Hey! Could you try the new version over at beta.festify.us (through a modern browser, not internet explorer) and check if that has the issue too? :)

**Comment by testr239** [comment]
That works much better, thank you. Only thing is that fallback playlists don't seem to work but that is understandable as it is a beta. 
If you were unaware of that the error is:
`Cannot read property 'isrc' of undefined` when trying to add or shuffle a playlist.

**Comment by NeoLegends** [comment]
> That works much better, thank you.

Great!

> Only thing is that fallback playlists don't seem to work but that is understandable as it is a beta.

Fixed! Thank you. :)
