### ISSUE TITLE
Control volume

### ISSUE THREAD

**Issue by acethatch** [Festify/app#133]
I think the output volume can be controlled. The Spotify web-player can do it.
Could be useful to do it in Admin mode from https://festify.us/party page

**Comment by NeoLegends** [comment]
We did not implement this for UX simplicity reasons previously. You were supposed to simply use the volume controls / system audio mixer of your device.

I‘m not sure about admin mode though, is certainly a nice feature to have. 🤔

**Comment by leolabs** [comment]
We could implement this, but I'm not sure how to do that UI-wise at the moment without sacrificing the current simplicity. We could hide it in settings but that'd be weird. Or we could expand the current track's height and add it there, but it may break the layout.

**Comment by acethatch** [comment]
And like this?
![festify volume](https://user-images.githubusercontent.com/360258/38236925-f9dc3b20-3725-11e8-8788-e250ad74128e.png)

**Comment by NeoLegends** [comment]
This doesn‘t work on mobile where you have very limited horizontal screen space.

**Comment by acethatch** [comment]
Something like this?

![festify volume2](https://user-images.githubusercontent.com/360258/38244406-d69d9888-373a-11e8-9245-4bde0c4185c8.png)

**Comment by NeoLegends** [comment]
Closing this since we're unsure how we could integrate it UI-wise at the moment. Once we figure out a way to do it cleanly we will think about implementing this again. :)
