### ISSUE TITLE
TV Mode & audio

### ISSUE THREAD

**Issue by jnieuwland** [Festify/app#141]
Hi! I love the TV mode visualisation, and it would be even greater if it also features audio playback. I use Chromecast to show the TV mode on a TV, but the audio is still on phone or laptop. It would be great if that audio could also play over the TV-connected stereo!

Cheers,
Jacco

**Comment by NeoLegends** [comment]
Hey!

This is kinda already possible today. If you open a Festify party and start the music, you can switch to TV Mode and the music will continue playing as normal. However, I‘m not sure whether this persists when the page is being cast to Chromecast. 

@mraerino do we have the ability to interact with pages while on the chromecast? We could offer something like a right-click menu for the admin to control the music while in TV Mode.

**Comment by jnieuwland** [comment]
Hi,

The music keep splaying, but in another tab. When you cast from Chrome, you only cast one single tab. So you can either cast the tab with the music player (not visually appealing for a party), or you cast the TV mode tab, but then you don't hear the music. Of course, I can hook up the laptop via audio cable to the stereo system, but it would be a lot nicer to do everything in one go!

Thanks!

**Comment by NeoLegends** [comment]
Ah, sure. I think the simplest and most pragmatic solution is to stop opening the TV mode in a new tab.
