### ISSUE TITLE
Question: Why does festify register as playback device?

### ISSUE THREAD

**Issue by Crease29** [Festify/app#151]
Hello,

at first I'd like to say thank you for developing Festify. Great idea and implementation!

I just had almost the same idea when I thought back to the times where we composed our party music with iTunes DJ. :laughing: 

I'm wondering why Festify registers as a playback device. I had the idea to dynamically fill a playlist based on the suggestions that the users will make. If it's empty, play a fallback playlist or start the artist radio of the last song or whatever... I think you guys also had this idea and I'd like to know why you have chosen the way with a playback device.

Is there any way to get in touch with one of you guys? :blush: 

Best,
Kai

**Comment by leolabs** [comment]
Hey Kai,
we use Spotify's Web Playback SDK to play the songs in Festify because it allows us to have more control over the playback. We tried the approach with a playlist aswell but that didn't work because Spotify doesn't refresh playlists while playing them so queue changes couldn't be reflected properly.

If you want to reach us via email, you can contact us at mail@festify.rocks :)

**Comment by Crease29** [comment]
Hey Leo,

thank you for your fast reply :blush: Have you also tried triggering the playlist to restart before every new song starts? This could let Spotify refresh the queue.

**Comment by leolabs** [comment]
We haven't tried that but using the Web Playback SDK we're able to run Festify standalone without Spotify having to be opened. This is a huge advantage and one of the reasons we chose to go down that path :)

**Comment by Crease29** [comment]
This is of course a powerful argument! Thank you Leo, have a nice weekend :)

**Comment by NeoLegends** [comment]
I'll close this for housekeeping purposes. Feel free to reopen this or open a new issue if you have any more questions. :)
