### ISSUE TITLE
Login failed with Facebook

### ISSUE THREAD

**Issue by Hypercookie** [Festify/app#155]
When starting a party in browser Spotify asks me to log in.Since my Spotify Premium account is linked to Facebook ,I have to log in with Facebook.Everything seems to work fine and I'm redirected back to Festify.But there I get the Error Massage "Token exchange failed with unknown: Failed to update user.."
I tried deleting my Cookies and Cache , removed Festify completly inside the allowed Apps from Spotify , nothing worked.

**Comment by NeoLegends** [comment]
Hey, thanks for the report!

Unfortunately, I can't see anything in the server logs from our side so I'm afraid I'll need some more help from you. :)

Could you try logging in again while having the developer console open and post the output here?
In Chrome: Right Click > Inspect Element > Console Tab. You might wanna turn on 'Preserve Log' to be able to follow through the redirects. Settings Cogwheel on Console Tab > Check Preserve Log.

**Comment by Hypercookie** [comment]
there you go

![image](https://user-images.githubusercontent.com/26379561/39405323-cc066aee-4ba3-11e8-9646-6cb5b5840f5f.png)

**Comment by NeoLegends** [comment]
Hmm, that ain't too useful. But I've updated our server to write all kinds of errors (including yours) to the logs. Could you try the exact same thing again?

**Comment by Hypercookie** [comment]
Did it.The log looks a little bit different so I appended it 

![image](https://user-images.githubusercontent.com/26379561/39405609-5a75517e-4ba8-11e8-9e1d-1ee0799fc99a.png)

**Comment by NeoLegends** [comment]
Hmm, seems like our systems don't like the Email address we're getting from Spotify. I'll take a look. :) Meanwhile, could you email (mail+git@festify.rocks) us the Email address you use for facebook?

**Comment by Hypercookie** [comment]
thats such a thing.Spotify also dont like the email adress.The problem is that i have an mobile Facebook account ,this means i dont have an email adress just a mobile number.After I realised that this is a problem I 
added an email adress to Facebook which Spotify is ignoring sucessfully.

**Comment by NeoLegends** [comment]
So Spotify also had issues with your E-Mail address?

**Comment by Hypercookie** [comment]
not exactly ...when I login to spotify trough Facebook everything works fine.But when I try to make a Device Password for some devices such as an Raspi or something like this , spotify reports a problem with my emailadress because they try to email me the password,but obviously they can't.

**Comment by NeoLegends** [comment]
Could you try logging in once more?

**Comment by Hypercookie** [comment]
Still an error , but another : 
"Token exchange failed with invalid-argument: null is not a valid email address"

**Comment by NeoLegends** [comment]
Ahh. Matches the behavior you're describing with creating custom account passwords. Spotify doesn't have an email for your account so it cannot give it to us, which causes the errors you're seeing.

Is there an email registered when you go to your account page (https://www.spotify.com/us/account/overview/)? If not, simply enter one and the problems should be gone and you should be able to use Festify. If there is one, well... I'm afraid we can't do anything about this for the moment then.

@leolabs Do we actually _need_ an email addresses for the user accounts? I think we're not using them at the moment (so we might be able to go without), but #154 is probably going to need valid addresses, isn't it?

**Comment by leolabs** [comment]
Afaik, Firebase needs an email address for every account. What we could do is generate a random email address for Spotify accounts that don't have their own because we have no use for them and Firebase won't check if they're valid anyway :p

**Comment by leolabs** [comment]
Maybe someting like <username>@spotify.festify.us

**Comment by Hypercookie** [comment]
of course i'll do

**Comment by NeoLegends** [comment]
> Afaik, Firebase needs an email address for every account. What we could do is generate a random email address for Spotify accounts that don't have their own because we have no use for them and Firebase won't check if they're valid anyway :p

What about #154? Won't that make account-merging / -linking super duper hard?

**Comment by leolabs** [comment]
Only if we want to use the email address to identify linked accounts. But in the current state we don't actually merge or link any accounts except for anonymous accounts to Spotify accounts and that should work no matter what the email address is :)

**Comment by Hypercookie** [comment]
So I talked to the Spotify people.Let me quote a bit ;)
I asked what exactly went wrong:

"Ah, I see. No worries. It's already a known issue from us and our tech peeps already on the look out. No need to worry.As a workaround, we're just updating it on our end to speed things up."

Which means you have to contact them.But the Spotify Guy sad it "should" be updating automaticly when you add your email to Facebook.

**Comment by Hypercookie** [comment]
And im able to log in now.You saved my day :D

**Comment by NeoLegends** [comment]
So if I understand you correctly people that have this issue need to contact Spotify support until they fix this on their end? :)

**Comment by leolabs** [comment]
@NeoLegends let's do the fix on our side aswell by generating an email address, to make it easier for new users to authenticate with Spotify.

**Comment by NeoLegends** [comment]
Lets open a new issue for that. :)

**Comment by leolabs** [comment]
Good idea 👍
