### ISSUE TITLE
prevent mixes from being added to the queue

### ISSUE THREAD

**Issue by Djfe** [Festify/app#166]
There are some mixes on spotify as well, but once you added soundcloud you should implement a setting that specifies a limit for the song length, so nothing above 10 Minutes can be added (mixes).

Or a different approach: always sort these types of tracks at the bottom of the list of tracks with the same vote count, so people can actually vote for them.

The problem: they can block the queue, as good as they might be.

**Comment by NeoLegends** [comment]
> There are some mixes on spotify as well, but once you added soundcloud you should implement a setting that specifies a limit for the song length, so nothing above 10 Minutes can be added (mixes).

Ah, I think the very old Festify had that to prevent exactly this. Noted down.

> Or a different approach: always sort these types of tracks at the bottom of the list of tracks with the same vote count, so people can actually vote for them.

I think keeping it simple is the way to go here. :)

**Comment by NeoLegends** [comment]
Closed in bb8feff61968bdd121cfed0bea91e8df87d6cefc
