### ISSUE TITLE
User cannot vote for songs until festify cookie is cleared

### ISSUE THREAD

**Issue by latchee** [Festify/app#176]
Hi there,

Somehow Festify stopped working for us. It had been working flawlessly until today (for a month or so).
Since today, people votes for new songs are not being taken into account. They can search for a song then they can click on the + sign, which changes into a heart. However, afterward, the song does not appear in the playlist.
I was able to fix the issue on a per computer basis by deleting the Festify cookie. Though it is a bit complicated to do that on everybody's computer.
Would you know another way to fix this issue?

Kind regards,
Lat

**Comment by NeoLegends** [comment]
Hmm, I cannot reproduce the issue. I can vote for tracks and add new ones to the queue.

Could you tell me which browser you and your people are using and whether the problem still persists? We've had some elevated error rates over the night, but they seem to be over.

**Comment by latchee** [comment]
Hi Neo,

Thank you for looking into this. We are on New Zealand time so might be a bit delayed for us to communicate :). So our users are on Chrome v 66 (up to date). It is affecting everybody that used Festify before yesterday. I am still getting some report today that people are affected by this bug. Clearing the cookies is currently the only solution I found to fix this.
Cookies that I delete are:
   - festify.us (2 cookies, database storage and local storage)
   - us-central1-festify-79b08.cloudfunctions.net (Channel ID)

Cheers,
Lat

**Comment by NeoLegends** [comment]
Could you send us the affected party ID via E-Mail? I have some suspicion but I'd need to take a look at the tracks to be sure. :)

Does the issue still affect you? The suspicion I've got should automatically clear itself after 12h.

**Comment by latchee** [comment]
Hi Neo,

Unfortunately, issue does not resolve itself after 12 hours. Moreover, users, for who I have deleted the cookie to solve the issue, are experiencing the same issue 24 hours after fixing it. Same as previously, deleting cookies solve the issue.
I have sent you the URL via email (on mail@festify).
Thanks again for your help.

**Comment by NeoLegends** [comment]
Thanks!

I think I found something. You are probably affected by a bug that is already fixed, but whose fix hasn‘t been released yet. I deployed a hotfix to that bug just now. Please see if that resolves the issues :)

**Comment by latchee** [comment]
Hi Neo,

Thank you very much for your help. I can confirm that the issue is fixed as I successfully tried Festify on several workstations without having to clear cookies beforehand.
(sorry to re-open the ticket ;) )

Cheers,

**Comment by NeoLegends** [comment]
Great! That‘s good to hear!

No worries, you‘re not „reopening“ anything. :)
