### ISSUE TITLE
Music redirected to admin computers

### ISSUE THREAD

**Issue by latchee** [Festify/app#180]
Hi Neo,

I have another issue/bug to report. If there is no music playing or it is stopped, when an admin starts to play some music, it redirects to their computer instead of the "master"/player computer. Hence, they have to remotely control the player computer to start playing some music.
Would you be able to help us on this one?

Kind regards,
Lat

**Comment by leolabs** [comment]
Hey Lat,
normally, this behavior only applies when there is no master player yet, like when you first open a party or when the current master player quits. It shouldn't happen when the music is paused.

Could you describe the steps you took to reproduce this bug? 

Kind Regards,
Leo Bernard

**Comment by latchee** [comment]
Ok, I think I understand.
For our case, we use Festify at work so that everyone can have a say in the music played :).
People are adding songs during the day which works well. But after work day, no more songs are added and in the end the playlist is exhausted (no more songs are in it). In the following morning, when people add new songs, they can't start the new playlist, an admin has to start it. That's when this new playlist is being played on the admin's computer instead of the player. Note that the master player computer stays on 100% of the time.
Would the fact that the playlist getting empty makes the master player quits?

Regarding the pause bug, I made a mistake and misunderstood what users told me. it works ok. Only issue is when an admin starts a playing music when playlist is empty, it starts to play on his computer.

Thank you for your help.

**Comment by leolabs** [comment]
Oh, that seems like a bug indeed. It shouldn't happen like that. We'll take a look into that soon and try to find a fix for it :)

**Comment by leolabs** [comment]
Hey Lat,
I've tried reproducing this error a few more times but couldn't get Festify to behave like you described. Could you try it again on your side and see if the problem still persists? If it does, could you describe the steps to recreate it as precisely as possible?

**Comment by latchee** [comment]
Hi Leo,
My apologies for replying so tardily. I have been quite flat stack lately.
So I have been doing some more testing and troubleshooting about this issue. And it seems I was wrong about the problem in the first place or the when it was explained to me. Since then, I have taken over the control of our Festify :).
So we have this machine that is used to host Festify to play our music in the office. Every morning when I try to start the music via admin login from my computer (not the same as the player) it does not start to play music. I can see the player advancing on the song but no music can be heard. If I remote on the host, I cannot see any sound being sent to the speakers (from the Windows Sound control panel). If I do a sound test, it works ok
To fix this issue, on the host, I have to clear Chrome cache and then load back in the party and login as admin. I can then start the music and people can vote into it (no need to recreate a new party).
Would you know why is this happening?
I am tempted to try again tomorrow with Firefox to see if this issue would come from Chrome itself.
Kind regards,
Lat

**Comment by leolabs** [comment]
Hey Lat,
thanks for the information. Would you mind telling us which version of Windows and Chrome you're using? This seems like an issue that is related to the Spotify Web Playback SDK we're using to play music in the browser.

**Comment by latchee** [comment]
Hi Leo,

Thank you for leading me toward the fix. We indeed have a pending update for Chrome, since we updated it to version 67.0.3396.79, it is working properly!
Many thanks.

Lat

**Comment by leolabs** [comment]
Nice, that's good to hear! I'll close this issue then :)

If you have further questions, don't hesitate to open a new one.
