### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by xer0design** [Festify/app#184]
Hey,

I've Festify setup and mostly running, it serves now and redirects over to spotify to login then kicks you back to the site but fails with an "Internal" error on the bottom left of Festify, developer console gives me this, an error about "No 'Access-Control-Allow-Origin' header", any ideas on how to fix? 

`
raven.js:1400 OPTIONS https://us-central1-*****.cloudfunctions.net/exchangeCode 404 ()
VM10579:1 Failed to load https://us-central1-*****.cloudfunctions.net/exchangeCode: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://htek.ie:3000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

The same thing happens with serve (htek.ie:3000) and a built version (build.htek.ie)

Cloudfunctions.net is a firebase domain so I've gone through the settings there but everything appears to be correct? The domain is added to the authroised domains and all that, any help would be appreciated!

**Comment by xer0design** [comment]
It does appear to be a CORS issue yeah, what exactly is involved in deploying the http functions for OAuth? I believe I've everything done but documentation for getting setup is light so I'm sure I've probably missed a step somewhere that I wasn't aware of

**Comment by NeoLegends** [comment]
Usually a `firebase deploy` (with the `firebase-tools` installed) will get everything going.

**Comment by xer0design** [comment]
That seems to fail, missing a file apparently? 

```
$ firebase deploy

=== Deploying to 'htek-festify'...

i  deploying database, functions
i  database: checking rules syntax...
✔  database: rules syntax for database htek-festify is valid

Error: functions/dist/index.js does not exist, can't deploy Firebase Functions

Having trouble? Try firebase deploy --help
root@instance-1:/home/xer0design/master/app# ```

**Comment by NeoLegends** [comment]
Yeah, the functions are written in TypeScript, so they need to be compiled before they can be deployed. Try `yarn deploy` from the `functions`-folder. It will compile the TS and deploy the compiled sources to Firebase.

**Comment by xer0design** [comment]
`yarn deploy` worked successfully (with one warning) and said everything deployed but I get the same error when I serve or build it

```
app/functions# yarn deploy
yarn run v1.7.0
$ firebase deploy --only functions

=== Deploying to 'htek-festify'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /home/xer0design/master/app/functions
> tslint --project tsconfig.json


WARNING: /home/xer0design/master/app/functions/src/index.ts[1, 13]: 'functions' is declared but its value is never read.

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /home/xer0design/master/app/functions
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/htek-festify/overview
Done in 16.78s.
```

**Comment by xer0design** [comment]
Okay I've tried just about every combination of deploying and no matter what I do I get the same error. I tried pulling a fresh copy of the repo and installing and initing and deploying and everything works up until I get to spotify and when they send me back to the site I get the exact same error, I'm completely lost

**Comment by NeoLegends** [comment]
Whats the exact URL thats 404ingn, including the part you star‘d out?

**Comment by xer0design** [comment]
https://us-central1-htek-festify.cloudfunctions.net/exchangeCode

**Comment by NeoLegends** [comment]
Seems like the functions aren't being deployed properly in your case. Normally the firebase tools should show a list of the functions that are deployed during deployment. Are you on a recent version of `firebase-tools`?

**Comment by xer0design** [comment]
Yeah I'm using the latest version, it's gives me a confirmation of database and functions getting deployed to the project, assuming it's relevent when I check firebase analytics it says database gets 1 connection, functions lists 0 connections

**Comment by NeoLegends** [comment]
I just edited my comment, please re-read :)

**Comment by xer0design** [comment]
Tried that and it said it deployed successfully again, however the same thing happens. Is the warning about functions never being called relevent? The service-account.json file from firebase is there yeah. I might start fresh on a new vm with a new firebase project and new copy of the repo to see if maybe something along the way broke something else, although when it's just this one error I doubt it'd be anything too catrostrophic. I tried just there putting a .htaccess file in the public build directory and enabling it in apache but that didn't fix anything either.

```
yarn build && firebase deploy --only functions
yarn run v1.7.0
$ tsc
Done in 5.58s.

=== Deploying to 'htek-festify'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /home/xer0design/app/functions
> tslint --project tsconfig.json


WARNING: /home/xer0design/app/functions/src/index.ts[1, 13]: 'functions' is declared but its value is never read.

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /home/xer0design/app/functions
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/htek-festify/overview
root@instance-1:/home/xer0design/app/functions# cd ..
root@instance-1:/home/xer0design/app# yarn serve
```

**Comment by NeoLegends** [comment]
> I tried just there putting a .htaccess file in the public build directory and enabling it in apache but that didn't fix anything either.

If the issue is that the functions aren't deployed properly this won't change anything, I guess.

> Is there a way to manually add the functions to the firebase project to see if that helps at all? As in do it through their dashboard.

Yeah, I think you can deploy functions via the google cloud console (not the firebase console, https://console.cloud.google.com/functions/list), but we've never done this before. Might be worth a try :)

It might also be the time to write an issue on https://github.com/firebase/firebase-tools about this. The whole thing seems very fishy. Could you maybe send a screenshot of the directory structure you're working with (a `tree` would work just as well)?

**Comment by NeoLegends** [comment]
Hey @xer0design any news?

**Comment by xer0design** [comment]
Hey @NeoLegends, sorry I just had my second kid arrive a bit early so I've been completely away from my pc for the last while, just trying again now while I have a few hours to relax! Made a new VM and went through setting everything up, fresh git pull from the repo and did what you suggested and got the same error on the site, then tried deploying the functions and got the following error

```

=== Deploying to 'htek-festify'...

i  deploying database, functions
i  database: checking rules syntax...
✔  database: rules syntax for database htek-festify is valid

Error: functions/dist/index.js does not exist, can't deploy Firebase Functions

Having trouble? Try firebase deploy --help
```

I must be doing something wrong but I really can't figure out what, I've no idea why the functions won't deploy

**Comment by xer0design** [comment]
If it's worth noting, the users show up on firebase no problem so that part appears to be working correctly

**Comment by NeoLegends** [comment]
> Error: functions/dist/index.js does not exist, can't deploy Firebase Functions

You sure you used the deploy script (`yarn deploy`)?

> If it's worth noting, the users show up on firebase no problem so that part appears to be working correctly

The rest should work then, no?

**Comment by xer0design** [comment]
``` root@instance-1:~/app/functions# yarn deploy
yarn run v1.7.0
$ npm run build && firebase deploy --only functions

> politics@ build /root/app/functions
> tsc && cp service-account.json ./dist

lib/spotify-auth.ts(6,61): error TS2307: Cannot find module '../spotify.config'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! politics@ build: `tsc && cp service-account.json ./dist`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the politics@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-14T20_08_42_160Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@instance-1:~/app/functions# 
```
Does that imply I should I rename spotify.config.js to spotify.config? Or is it something else?

**Comment by NeoLegends** [comment]
Name it `spotify.config.ts`, notice the `.ts`.

**Comment by xer0design** [comment]
Sorry I meant in the root directory, it has the `.ts` in the functions directory, I assumed by the `../` that it was referring to the root. Here's the files in `/`
```
assets  
common.config.js     
firebase.config.js  
functions     
node_modules  
prepare-env.js  
rollup.config.js   
src            
tslint.json
build   
database.rules.bolt  
firebase.json       
netlify.toml  
package.json  
README.md       
spotify.config.js  
tsconfig.json  
yarn.lock
```

Here's what in `/functions`
```
dist  
firebase-debug.log  
index.ts  
lib  
node_modules  
package.json  
service-account.json  
spotify.confifg.ts  
tsconfig.json  
yarn.lock
```

**Comment by NeoLegends** [comment]
> spotify.confifg.ts

**Comment by xer0design** [comment]
...I have never felt like a more worthless programmer in my life. If that's it I'm going to cry, let me give that a shot

**Comment by xer0design** [comment]
They deployed. They actually deployed. I feel terrible and you're amazing, let me know if there's a donate button anywhere where I can send a small thank you. I'll also write a how to setup section for the readme and do a pull request when I have some time to do it right. Serving still failed, however, the error pushed to firebase though so I can debug from here, maybe there's something wrong in one of the spotify files, the error is below. I'll see if I can figure it out, unless you recognise it? 
```
Unhandled error { Error: getaddrinfo ENOTFOUND accounts.spotify.com accounts.spotify.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'accounts.spotify.com',
  host: 'accounts.spotify.com',
  port: 443,
  attempts: 5 }
```

**Comment by xer0design** [comment]
Okay research says I need a paid firebase plan to use these functions, I'll enable billing now and see.

**Comment by xer0design** [comment]
It worked! It fully works. I'll make a setup doc in the coming days, thanks so much for your help and patience.

**Comment by leolabs** [comment]
That's great to hear! We're looking forward to your documentation :)

If you want to donate, there's a donation link at the bottom of our [homepage](https://festify.rocks).

**Comment by goshdark138** [comment]
> It worked! It fully works. I'll make a setup doc in the coming days, thanks so much for your help and patience.

please setup doc

**Comment by goshdark138** [comment]
@xer0design please setup doc
