### ISSUE TITLE
Add support for Custom TV instruction/message line and URLs

### ISSUE THREAD

**Issue by Computr0n** [Festify/app#190]
I set up my Google domain to have one of its subdomains forward to my party room directly.
So, e.g., [music.mysite.com](music.mysite.com) goes to [https://festify.us/party/-NOT_R3al1yThEUrl
](https://festify.us/party/-NOT_R3al1yThEUrl
)
It's really handy to be able to give guests this URL, but it would be nice to be able to edit the message/URL that is shown on the TV site so it doesn't tell them these complicated steps:
```
Add your songs on www.festify.us
Party Code 123456
```
and instead had the option for the room to specify a custom message with perhaps a corresponding URL like so:

```
Go to music.mysite.com to add songs
```

**Comment by Computr0n** [comment]
I just realized you already have support for custom TV mode text.... How did I miss that???

That said, I would love to be able to remove the line below it:
```
Party Code 123456
```
And to be able to use that second line as part of a multiple line custom TV message.

**Comment by NeoLegends** [comment]
Hey! Great to hear you figured it out.

> That said, I would love to be able to remove the line below it:

We're not so sure about this right now. We've had some internal discussion, but decided against allowing the removal of the badge for simplicity reasons, at least for the close future. To give an example: Right now, every line in the TV Mode has its own font settings (think size, boldness, etc.) that are specifically fine-tuned for the text on that line. If we allowed the badge to be removed and the text to be multiline, we'd have to consider this and find a solution that looks satisfyingly. The main point, however, is that Festify is - after all - still supposed to be dead simple to use and this kinda contradicts that. :)

If you have any more thoughts regarding this, please feel free adding them here, we're not omniscient after all.
