### ISSUE TITLE
Musixmatch Integration

### ISSUE THREAD

**Issue by Computr0n** [Festify/app#191]
[Musixmatch ](https://www.musixmatch.com/)is a service that integrates with the Spotify API to get live synced lyrics with the current song. It works really well to have the windows 10 app open alongside this website, but I wonder if the TV mode could somehow integrate with their service and automatically show lyrics for the guests.

**Comment by NeoLegends** [comment]
Hey!

Musixmatch is extremely expensive for small devs like us (at least $1000/mo), so we‘ll have to pass on this.

**Comment by leolabs** [comment]
For the $1000/mo we wouldn't even get the synced lyrics. That'd be more expensive than that :/

It's a really cool idea, and we may implement it if there's a service which does that for free, but I doubt that there will be one any time soon.
