### ISSUE TITLE
Ability to export the playlist to spotify

### ISSUE THREAD

**Issue by kimrtaylor** [Festify/app#192]
After people have added tracks and voted, I'd like to save the playlist for future use. Ideally there would be the ability to export it to a new playlist in Spotify. 

Perhaps even better would be if Festify continuously syncs with the fallback playlist in Spotify, so the original Spotify playlist is kept up to date (and vice versa: if the fallback playlist has a track added to it in Spotify, it would appear in Festify).

**Comment by NeoLegends** [comment]
Great suggestion! We've already got an issue for this over here: #126. Closing this as duplicate, please feel free to add your thoughts to #126 :)

**Comment by kimrtaylor** [comment]
Ah, thanks! Sorry I missed that one when checking through existing issues.
