### ISSUE TITLE
Cannot create party

### ISSUE THREAD

**Issue by charliwest** [Festify/app#232]
Every time I click create it takes me to the join page, am I missing something?

**Comment by NeoLegends** [comment]
Hey!

Are you using iOS or Safari?

**Comment by NeoLegends** [comment]
Yes, unfortunately this is the only solution for the moment. Safari cannot play Spotify music due to technical limitations (Safari doesn't support Spotify's DRM scheme).

**Comment by barriosnahuel** [comment]
Hi, I'm facing this issue on Chrome and Android 8.x.. do you have any workaround to create it?

**Comment by leolabs** [comment]
Creating a party on Android is still a bit buggy, but if you want to use it, you can use Chrome's 'Request Desktop Version' feature. You should leave your browser in the foreground while using Festify on Android though. If you don't, chances are that Chrome will kill the tab sometime in the future.

**Comment by barriosnahuel** [comment]
Perfect! Thank you very much, it's working now. What plans do you have about an Android app? Perhaps I can help on that

**Comment by leolabs** [comment]
For now, we don't have any plans about mobile apps as we lack the expertise in native app development. If that changes in the future, we'll let you know :)

**Comment by Giazzo20** [comment]
So, same to me, every time I touch on create party, it takes me to the join page. I'm using Samsung Galaxy S9+ with Chrome, so maybe it's an Android's problem. Too bad for that...

**Comment by leolabs** [comment]
To create a party, you'll need a computer running Firefox or Chrome. Currently, playback on mobile is not supported :)
