### ISSUE TITLE
no play sound

### ISSUE THREAD

**Issue by goshdark138** [Festify/app#241]
the track is being played, but it does not sound.

please chek: http://68.183.152.205:3000

**Comment by goshdark138** [comment]
@NeoLegends some help?

**Comment by NeoLegends** [comment]
Something seems wrong with the playback SDK.

Can I ask you why using festify.us is not acceptable for you?

**Comment by goshdark138** [comment]
> Something seems wrong with the playback SDK, but I can't really tell you what it is either.
> 
> Can I ask you why using https://festify.us is not acceptable for you?

I want to translate it into Spanish and change some icons

**Comment by leolabs** [comment]
This seems weird. I just tried it myself on your domain and get the same results. Could it be that we're using an older version of Spotify's SDK in our production build and a newer version breaks? Seems unlikely because we have a yarn.lock but it could be the source of that problem 🤔

**Comment by NeoLegends** [comment]
> Seems unlikely because we have a yarn.lock but it could be the source of that problem 

We load the SDK via script tag, because it's not published to npm. So could be that, but I suppose it's something else.

Don't you need to white-list your domain with Spotify somehow? @goshdark138 did you do that?

**Comment by goshdark138** [comment]
do not take the step, where I add it?

**Comment by goshdark138** [comment]
@leolabs which version are implemented in production?

**Comment by goshdark138** [comment]
According to the documentation of the SDK it is necessary that the Redirect URIs this https.

Everything works perfectly. Thank you very good job

**Comment by NeoLegends** [comment]
Great!

Just a nit: it's good practice to close issues once they're no longer relevant / resolved.
