### ISSUE TITLE
Please help to configure production release

### ISSUE THREAD

**Issue by goshdark138** [Festify/app#242]
Hi, I'm sorry to write you for something as simple as this, but I need help in assembling festify in production mode.

how do I do so that the server does not show 404 when entering a url as for example:

https://festify.us/party/-LSw8eNTmj-02Z_aQLnn
 
http://68.183.144.162/party/-LSw8eNTmj-02Z_aQLnn

where can I make a donation?

**Comment by goshdark138** [comment]
@leolabs @NeoLegends  I would appreciate if you can give me the terms that I should look for to make a correct server configuration

**Comment by NeoLegends** [comment]
I can recommend https://netlify.com

**Comment by leolabs** [comment]
I'm gonna close this issue for inactivity. If you have further questions, feel free to open a new one :)
