### ISSUE TITLE
Firebase Auth Error

### ISSUE THREAD

**Issue by exp625** [Festify/app#269]
After building and serving the app I get the following Error in Sentry:

**xhr:** `POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=*** [400]`

**Error:** ```Error: {"error":{"code":400,"message":"ADMIN_ONLY_OPERATION","errors":[{"message":"ADMIN_ONLY_OPERATION","domain":"global","reason":"invalid"}]}}```

The corresponding firebase error code ist `auth/internal-error`

I have checked the firebase admin sdk and set the client email adress in my google cloud console to be a firebase admin.

**Comment by stephan2002** [comment]
Did you already fix this? I also have this error

**Comment by NeoLegends** [comment]
Did you enable anonymous user sign in in the Firebase console?

**Comment by stephan2002** [comment]
Hi! No I don't think so. Can you tell me where to find that option, and if
it must be enabled or disabled?

Op wo 28 aug. 2019 10:12 schreef Moritz Gunz <notifications@github.com>:

**Comment by NeoLegends** [comment]
It needs to be enabled, see https://firebase.google.com/docs/auth/web/anonymous-auth for more information.

**Comment by stephan2002** [comment]
Hi, that's working now. But when I try to login with Spotify to create
party it says illegal scope.

Op wo 28 aug. 2019 12:40 schreef Moritz Gunz <notifications@github.com>:

**Comment by stephan2002** [comment]
Hi, I tried some things but still can't get it to work. Can you tell me how to remove the illegal scope error?

**Comment by stephan2002** [comment]
I fixed the issue, but now I am getting the following in firebase:

Unhandled error { Error: getaddrinfo EAI_AGAIN accounts.spotify.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'accounts.spotify.com',
  host: 'accounts.spotify.com',
  port: 443,
  attempts: 5 }

**Comment by NeoLegends** [comment]
Did you set up a paid Firebase project (as instructed in the readme)? Unpaid Firebase Cloud Functions do not have access to the network (which results in the error you're seeing here).

**Comment by stephan2002** [comment]
Aah okay, which payment plan is best to choose and what is the average
monthly cost?

Op do 29 aug. 2019 12:41 schreef Moritz Gunz <notifications@github.com>:

**Comment by NeoLegends** [comment]
https://firebase.google.com/pricing

**Comment by NeoLegends** [comment]
I'd go with pay as you go.

**Comment by stephan2002** [comment]
And what will then be the average monthly cost?

Op do 29 aug. 2019 12:43 schreef Moritz Gunz <notifications@github.com>:

**Comment by NeoLegends** [comment]
Most certainly 0€, because the free usage from the Spark plan is included (assuming you don't exceed the limits, which are generously large).

**Comment by stephan2002** [comment]
Aah okay. Do you know if it is possible to buy without credit card? Because
firebase keeps asking for a credit card, but I don't have one.

Op do 29 aug. 2019 13:04 schreef Moritz Gunz <notifications@github.com>:

**Comment by NeoLegends** [comment]
I am not sure. I think you should consult the Firebase docs / Google for that.

But you can always our the hosted version over at https://festify.us.

**Comment by aabi0044** [comment]
@NeoLegends in my case I am using signup with email and password and I also enabled that from console but why in that case I am getting this error?

**Comment by NeoLegends** [comment]
@aabi0044 did you go through all steps in this issue? Like enabling anon users, paid project, etc. ?
