### ISSUE TITLE
No Sound while playing - Failed to find spotilocal url

### ISSUE THREAD

**Issue by NeroAngelo12** [Festify/app#286]
Hi,

I have a problem with music playback in both the web player and the Windows application.
The "Playing-progress-bar" is moving but there is no Audio. 

Windows App -> 0.2.10
I tried the latest version of Chrome and Firefox.

The desktop app displays an error message:

"Could not initialize playback: It looks like Spotify isn´t open. We failed to find spotilocal url with ports in range 4370-4380."

Like here -> -> -> 
![festifyissue2](https://user-images.githubusercontent.com/47294660/66948509-21b66a00-f055-11e9-81a7-85dbb2d195df.jpg)

Spotify's open. 
Do I need to open these ports on my router? 

Is it possible that this problem is caused by the 3-month trial version I am currently using?

**Comment by NeoLegends** [comment]
Hey!

The desktop apps are not supported anymore and will probably not work anymore at all. Did you try the version over at https://festify.us?

**Comment by NeroAngelo12** [comment]
Thanks for the quick answer.

Too bad to hear that the application can no longer be supported.

i was at the Festify.rocks so far. 
Now everything is working perfectly.
The solution can be that simple - thank you.

Thanks again for the quick help now the party can start.

**Comment by leolabs** [comment]
Just to clear things up, the Festify web app is still supported. Only the desktop app is deprecated because it used inofficial APIs and was too unstable to properly maintain it.

I'll close this ticket for now. Feel free to open a new one if you have any further questions :)

**Comment by Juoper** [comment]
I think this issue should be closed
