### ISSUE TITLE
Cannot use admin mode

### ISSUE THREAD

**Issue by SpartanTek** [Festify/app#292]
When I try to login using admin mode I get the error that a email address linked to a account already exists and the token exchange has failed

**Comment by leolabs** [comment]
Hey @Gamn69,
could you tell me which service (Google/Facebook/Spotify/etc) you're using to log into the admin mode? Logging in with Spotify should be the best option here. Does one of the other services work better?

**Comment by Gamn69** [comment]
I am using spotify

**Comment by Gamn69** [comment]
Some extra information is I used to have a different Spotify account but then deleted due to an issue and recreated it with the same email. From what I can infer is that my email is linked to my previous account and Festify is not realizing that my previous account got deleted. Any way to fix this?

**Comment by leolabs** [comment]
Oh, that could be the problem! If you send us your old and new email addresses, we can delete them from our user database so you can log in again :)

**Comment by Gamn69** [comment]
Done, sent to mail@festify.rocks

**Comment by Gamn69** [comment]
Any update on this?
