### ISSUE TITLE
[Suggestion] Support for tvOS

### ISSUE THREAD

**Issue by gubraun** [Festify/app#297]
I was wondering if you ever thought of support for tvOS ie. Apple TV? And whether it would work, given the Spotify Player SDK platform limitations?

Why?
Currently, I need a PC to start a party. I need to redirect the audio to a speaker system (line out, Bluetooth, Airplay, whatever). I also would typically redirect the screen to my TV, so everybody can see the current queue on a big screen. All this is already in place for by Apple TV. I just would need to be able to run the app on it (which is not possible, as tvOS doesn't have a browser).

I wonder how hard it would be to turn the current app into a tvOS app using [TVMLKit](https://developer.apple.com/documentation/tvmlkit). 

I don't have much experience here, but I'd be happy to look into this. But I wanted to hear your thoughts first.

Greetings from Aachen :-)
Gunnar

**Comment by leolabs** [comment]
Hey @gubraun,

We've thought about that idea as well, but unfortunately, we're limited by Spotify's SDK which doesn't run on tvOS. As a workaround, we've often just used AirPlay to cast audio and the screen from a computer to an Apple TV which works fine.

**Comment by gubraun** [comment]
OK - that just saved me some effort :-) Too bad.
