### ISSUE TITLE
Cannot create party in Safari

### ISSUE THREAD

**Issue by smnmsr** [Festify/app#300]
When i click the 'CREATE A PARTY'-Button in my Safari browser, I am redirected to https://festify.us/?create. There I cannot Login or create a party, I can only enter a Party Code.

When i press the same button in Chromem I am redirected to the same page, but there an addition button appears which says 'Login to create Party'.

**Comment by NeoLegends** [comment]
This is the expected behavior. Safari does not support Spotify Web Playback, which is why you cannot create parties in there.

**Comment by leolabs** [comment]
@NeoLegends since multiple users have reported this now, maybe we can show a warning when a user opens the page with `?create` and the browser isn't supported. This might be better UX than just not showing the button.

**Comment by muescha** [comment]
I just noticed I can play Spotify in safari ( at https://open.spotify.com/ ) 

So maybe there is no restriction with safari on iOS anymore?

**Comment by leolabs** [comment]
I've just deployed a new version that allows you to creates parties on Safari. There's a little bug still where you need to press the play button twice the first time to start playback, but other than that it works smoothly – even on iOS and iPadOS as long as you keep the browser in the foreground :)
