### ISSUE TITLE
Output volume setting needed for sharing music in meeting - workaround?

### ISSUE THREAD

**Issue by grantbowering** [Festify/app#303]
I've been sharing Festify music on all my Zoom social events, by: 
 - dedicating a separate computer as a music server for the duration of the meeting, 
 - with its zoom camera set to a screen capture recorder (open to Festify in TV mode), 
 - and its zoom microphone input set to the output of a virtual mixer 
    - (engaging zoom's Turn On Original Sound feature so that it doesn't try to filter that music for spoken vocal content).  

This allowed me to: 
 - decrease the virtual out volume -35ish dB before it hit the meeting, so that it was actually background music level and people could converse over it, 
 - show attendees what's playing and what the room code is, via the dummy user's video feed, 
    - while avoiding the rearranging the meeting layout and dominating it that "share screen" would cause.

This worked beautifully for 6 months.

Unfortunately, as of having updated the zoom client on that machine last week, this suddenly no longer works correctly; the music is now silent most of the time and occasionally briefly cuts in.  
(I guess with this "background noise suppression setting" feature they rolled out, they must have tweaked some of the underlying dsp code such that it applies some noise gating or something, despite Turn On Original Sound being engaged... ugh.  I can't really seem to convince support that a bug has been introduced, though, so 🤷‍♂️.)

So I have to abandon the "music as microphone" approach, and switch to doing it this way (which admittedly is a feature I didn't know existed until now):

![image](https://user-images.githubusercontent.com/2152220/91670333-ac6f4e80-ead9-11ea-8d44-4236209656b8.png)

The problem with that is, it's now IMPOSSIBLY LOUD again, because I have no opportunity to intercept that signal and turn the volume down.

I saw issue #133, where a volume control UI was discussed, but deprioritized because of a lack of anywhere sensible to put it... 
but since Zoom support can't seem to help me beyond "use audio sharing, if it's too loud turn down the volume at the source", it's kind of a necessity if I want to keep having music (which I do!).

I did, however, find a workaround for now, I'm just not sure of its stability/reliability:

If I open up the Spotify app while using Festify, it shows a `Listening on Festify` banner like any other non-local playback, and the volume control on it actually affects the Festify playback volume!
![image](https://user-images.githubusercontent.com/2152220/91668864-572d4000-eacd-11ea-9ffe-4d89f21ec15c.png)

Honestly, I'm surprised this works, and I'm wondering if I'm going to get any flaky side effects by working around it this way...

**Comment by leolabs** [comment]
Hey @grantbowering,
thanks for your feedback!

I think the workaround you're using doesn't have any bad side effects, it's a good way to control the volume. To keep Festify clean, we decided against adding a volume slider to the app because, in 95% of the scenarios, you can just turn your computer's volume down.

@NeoLegends do you think this workaround might be a good thing to add to the FAQs?

**Comment by grantbowering** [comment]
(honestly, Zoom broke the way quiet background music performs when shared as computer sound too, like 5 days after I wrote this, so I've been moving all my social meetings to Discord, which doesn't mess with sound when you're piping it through a bot ([discord-audio-pipe](https://github.com/QiCuiHub/discord-audio-pipe)) plus lets everyone individually control everyone else's volume.  So, bye Zoom.  It's a little clunky because Discord bots can't share video, so the festify TV mode screen has to come from a separate real user than the stereo audio which you can only get from a bot user, but that's an okay price to pay for me.)
