### ISSUE TITLE
Unable to add explicit tracks to the queue,

### ISSUE THREAD

**Issue by MrCodZilla** [Festify/app#305]
Hello, 

as of yesterday, I haven't been able to search for any explicit tracks to add to the queue within a party,

I normally make a party and then send the link to a music request group and have roughly about 4-6 people join via the link to add songs.

I have gone through the settings and did see the box which allowed guests to add explicit tracks but doing some testing with it on/off doesn't appear to be working, ( also doesn't work for me, the party owner ).

Doing some research doesn't give many results on this and this may be the first time this has happened. 

Also have been through my Spotify settings ( web version too) and can't see anything as to why this suddenly changed.

**Comment by leolabs** [comment]
Hey @MrCodZilla,

it's weird that this suddenly changed as we haven't made any changes to Festify in a few months. I've just tried reproducing it and found the same issue to happen on my side.

**Comment by leolabs** [comment]
I just pushed a fix for it. Spotify weirdly enough marked all explicit tracks as `is_playable: false`. I've removed this filter so you can now see explicit tracks again :)
