### ISSUE TITLE
Is Festify now broken?

### ISSUE THREAD

**Issue by elcapitantommy** [Festify/app#308]
Hi, I’ve just read that you aren’t actively developing Festify anymore and it no longer appears to work - it plays a song for 10 secs and then fails. Is this due to Festify being broken or a problem at my end? Thanks!

**Comment by leolabs** [comment]
I just tried it on my side with the latest version of Chrome and it works as expected. When the song fails, do you see any errors in the web inspector's console?

**Comment by elcapitantommy** [comment]
Hi - I’ve just tried using a different machine and it’s working as expected thanks - I’ll close this down - thanks for the quick response!
