### ISSUE TITLE
Festify autopauses 

### ISSUE THREAD

**Issue by kathynew70** [Festify/app#310]
First off .... I LOVE festify!! Great for parties! 
Recently I noticed that after three songs, Festify will auto pause. I have tried flushing the queue, updating browser, different browser, updating spotify, and restarting PC. 
I have tried with both Chrome and Firefox and it does the same thing. 
Any suggestions would be super appreciated!
Thank you!
Kathy

**Comment by leolabs** [comment]
Thank you for the issue report! I think this is related to #272. We're on it, but haven't found a solution for it yet :)

**Comment by kathynew70** [comment]
I did some further testing and found that it only happens when I have TV
mode open in another window.
Not sure if that helps in debugging or not, but wanted to pass along.

**Comment by leolabs** [comment]
Thank you for the hint, that should help us in finding out what's actually causing the problem.
