### ISSUE TITLE
Playback is broken or inconsistent. 

### ISSUE THREAD

**Issue by weselder** [Festify/app#313]
Just today, I noticed that I could on get more than one song to play.  The first song would end and playback would stop...  And, I could never get the next/second track to play at all.  On a PC with Chrome and Edge, both demonstrated the same consistent problem.  Now that I'm on a different Network leveraging a Mac and safari, still seeing the same problem. Yet the web app for Spotify plays fine for all browsers. 

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/13191465/168451676-0c130826-c654-4037-9ae9-08d73dea1d7d.png">

**Comment by weselder** [comment]
The skip button does not work at all.

**Comment by 011i** [comment]
Yep, same Problem here :-/

**Comment by wreaker001** [comment]
Same problem here on MacOS and Windows. Mobile and Desktop. The beginning of a track is looping 4 times and after the song has ended it does not switch to the other track automatically. Unable to switch songs by hand as well.
I would be so grateful if you could fix it.

**Comment by ioneegh** [comment]
Would be very nice if this could be fixed soon. :)

**Comment by ceddesrochers** [comment]
Can confirm I've got the same issue with Chrome, firefox as well as other browsers. 
Will subscribe to be in the loop, because I really like this web app!

**Comment by leolabs** [comment]
I think I found the bug and fixed it in 5ef4227464768a8b6afc7aa369cc486c6ee38fa3. Let me know if the app works on your side now :)

**Comment by SingularityOS365** [comment]
> I think I found the bug and fixed it in [5ef4227](https://github.com/Festify/app/commit/5ef4227464768a8b6afc7aa369cc486c6ee38fa3). Let me know if the app works on your side now :)

Thank you so much! It is now working. We have a party tomorrow and we're hoping it'd be fixed. Is there a way I can donate as thanks?

**Comment by leolabs** [comment]
That's great to hear, thanks for your feedback! We have a donation link at the bottom of our website, festify.rocks :)
