### ISSUE TITLE
Share button doesn't work

### ISSUE THREAD

**Issue by Juoper** [Festify/app#316]
The share button in the admin panel only throws an error in the console. See this pastebin: https://pastebin.com/kmC5Yfpx

**Comment by leolabs** [comment]
Thanks for the bug report! Could you elaborate a bit on which browser you used this on?

**Comment by Juoper** [comment]
I used google chrome on Version 102.0.5005.63

**Comment by Juoper** [comment]
I tried it just now and it worked fine
