### ISSUE TITLE
Stop after first song finished

### ISSUE THREAD

**Issue by Plati1710** [Festify/app#325]
Hello together,
I was looking for a tool like festify for our wedding. I'm excited!
However, I despair of the autoplay function. After the first song, the list stops. Playing -> Paused, next Song is marked as "Fallback Track". So i would say, everything looks fine. Only when I skip manually does festify jump to the next song. When looking for a solution here in the forum I tried everything possible. Unfortunately without success. What am I doing wrong?

Thanks in advance

**Comment by leolabs** [comment]
Does this happen in every browser? I'd generally recommend using Festify in Chrome as it seems to be most stable there.

**Comment by almostcool92** [comment]
Hey, I'm also having this issue. Have tried 3 different browsers including Chrome. Others used were Opera and Edge.

**Comment by Plati1710** [comment]
> Hey, I'm also having this issue. Have tried 3 different browsers including Chrome. Others used were Opera and Edge.

Same here, tried chrome, edge and mozilla firefox. I also closed everything on my smartphone (spotify, festify as admin etc.) and also on the PC. I checked up every setting.

Everything looks fine, i see the fallback songs and if my partner quoted one it jumps to the top of the list.
except that after the first song it continues automatically :_( I despair, such a great program for my wedding.

**Comment by herberanton** [comment]
Same issue with Firefox. Stops after the first song.

**Comment by leolabs** [comment]
I just managed to reproduce the bug on my end as well. Will try to implement a fix for it tomorrow :)

**Comment by Plati1710** [comment]
> I just managed to reproduce the bug on my end as well. Will try to implement a fix for it tomorrow :)

This would bei sooo amazing for our Wedding on saturday :)

**Comment by Homir11** [comment]
> 

Would be great Leo, I'm also facing the same issue right now. Let us know. Thanks!

**Comment by leolabs** [comment]
I just deployed a fix, could you check if it works for you now?

**Comment by Plati1710** [comment]
It works!!! We are soooo happy!

**Comment by NeoLegends** [comment]
This seems fixed! Let us know if there‘s anything else to do.
