### ISSUE TITLE
Crash on Android Emulator / Building and Running in General

### ISSUE THREAD

**Issue by amenk** [Festify/app#45]
Directly after starting it, the app crashes.

logcat:

<details>

	03-02 22:40:02.849  1757  3038 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{6006db6 0:rocks.festify.app/u0a61}
	03-02 22:40:02.960  1757  3038 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=rocks.festify.app/.MainActivity bnds=[773,1102][997,1326] (has extras)} from uid 10012 on display 0
	03-02 22:40:03.043  1757  2407 I ActivityManager: Start proc 3065:rocks.festify.app/u0a61 for activity rocks.festify.app/.MainActivity
	03-02 22:40:03.112  3065  3065 W System  : ClassLoader referenced unknown path: /data/app/rocks.festify.app-1/lib/x86_64
	03-02 22:40:03.290  3065  3065 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3065 (cks.festify.app)
	03-02 22:40:03.343  3084  3084 F DEBUG   : pid: 3065, tid: 3065, name: cks.festify.app  >>> rocks.festify.app <<<
	03-02 22:40:03.422  1757  1822 I WindowManager: Destroying surface Surface(name=Application Error: rocks.festify.app) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8079 android.os.Handler.dispatchMessage:102 
	03-02 22:40:03.766  1757  3089 W ActivityManager:   Force finishing activity rocks.festify.app/.MainActivity
	03-02 22:40:03.908  1757  2407 I ActivityManager: Process rocks.festify.app (pid 3065) has died
	03-02 22:40:04.322  1757  1822 I WindowManager: Destroying surface Surface(name=Starting rocks.festify.app) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.AppWindowToken.destroySurfaces:365 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:196 

</details>

**Comment by mraerino** [comment]
Thanks for reporting 🎉

Are you trying to build for x86_64?
I'm pretty sure the Spotify SDK will only work on ARM

**Comment by amenk** [comment]
Looks like .. ARM emulator is so slow... any other way to test quickly?

**Comment by mraerino** [comment]
We will provide APK builds when we are entering closed beta, but for now, building manually is your only option, sorry.

**Comment by amenk** [comment]
I mean .. testing when developing :-) Do you develop with real devices? or `cordova serve` ? or the arm emulator?

**Comment by NeoLegends** [comment]
The Spotify SDK rund on x86 as well. We're devving using the emulator as well as real devices (I actually run the x86 emulator myself).

**Comment by mraerino** [comment]
Oh, you are right. On mine too.
Then just let me complete a fuller readme so when can see if we are on the same page about the build.

**Comment by NeoLegends** [comment]
@amenk Could you precisely follow the readme and try again? :)

**Comment by amenk** [comment]
Thanks for the readme.
I did all the credential stuff and tried again on an ARM 32 bit device in the emulator .. also crashes...

On my phone I get instead 
`Application Error - ERR_FILE_NOT_FOUND (file:///android_asset/www/app.html)`

**Comment by amenk** [comment]
Running `gulp serve` I am getting an auth error - 

Also it is interesting to mention, to not run it via http + the external IP but via localhost, otherwise you get

`Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).` (but localhost counts as sercure origin)

**Comment by amenk** [comment]
> On my phone I get instead
> Application Error - ERR_FILE_NOT_FOUND (file:///android_asset/www/app.html)

This is fixed now -- I think I forgot `gulp build-cordova` - but now I get the authentication problem as well on the phone.

Emulator is still not running.

**Comment by amenk** [comment]
I think the problem was that I tried to run on an emulate without Google APIs ... works now.

But still "Authentication problem"
