### ISSUE TITLE
Migrate Spotify auth calls to Firebase functions

### ISSUE THREAD

**Issue by mraerino** [Festify/app#51]

**Comment by NeoLegends** [comment]
I wonder what is going to happen to the existing AWS Lambda functions.

AWS Lambda is pretty general and they make a nice starting point for peoply trying out our plugin. If we switched those over to Firebase, they would buy into a monolithic product they might not need 90% of. 

IMO we should switch the functions used by Festify over to Firebase to simplify deployment but leave those in the `cordova-spotify` repo untouched.
