### ISSUE TITLE
Make TV mode layout responsive across all screen sizes

### ISSUE THREAD

**Issue by NeoLegends** [Festify/app#53]

**Comment by mraerino** [comment]
Please provide a better description :wink:

**Comment by NeoLegends** [comment]
AirPlay casts 2nd screens in 720p and the TV mode cannot properly adapt to that.

**Comment by leolabs** [comment]
Wtf, that's good to know. Is there maybe a way to force 1080p? While it is
possible to adapt the TV mode properly, 720p on a big screen looks kind of
ugly.
Moritz Gunz <notifications@github.com> schrieb am So. 26. März 2017 um
13:07:

**Comment by NeoLegends** [comment]
There are things like [display modes](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/WindowAndScreenGuide/UsingExternalDisplay/UsingExternalDisplay.html#//apple_ref/doc/uid/TP40012555-CH3-SW4) in iOS

**Comment by leolabs** [comment]
Cool, I'll implement that in the cordova-external-screen library 😊
Moritz Gunz <notifications@github.com> schrieb am So. 26. März 2017 um
13:13:

**Comment by NeoLegends** [comment]
If we're going to render 1080p, we're are going to have to work around the performance problems of CSS blur...

**Comment by NeoLegends** [comment]
@leo I think I'd favor an approach where we make the TV mode layout responsible. Working with screen modes can be tricky, especially because not every screen supports every screen mode.

**Comment by NeoLegends** [comment]
Fixed.
