### ISSUE TITLE
Wrong response type: Error

### ISSUE THREAD

**Issue by NeoLegends** [Festify/app#67]
Playback cannot be initialized in real android devices.

![Error Description](https://pbs.twimg.com/media/DA-vLXFXkAEHAJQ.jpg:large)

**Comment by NeoLegends** [comment]
Closing due to new plugin version. Probably irrelevant right now.

**Comment by Sinuce** [comment]
I have the same issue.
How do I fix or circumvent it?

Occurs as soon as I start a new party.

Android 6.0.1
Festival 0.1.9
Nexus 5
Spotify Family (= premium)

**Comment by Sinuce** [comment]
Workaround:
Use Windows desktop version of Festify :)

**Comment by notflip** [comment]
Is this still broken on OSX? Working on windows? Thanks!
