### ISSUE TITLE
Login through Facebook

### ISSUE THREAD

**Issue by BillyNovel** [Festify/app#90]
Hi everyone,

Since my Spotify account is linked to FB, I can't connect without it and when I do, I have to retry multiple times to pass through "Cookies disabled in your navigator error" and get the window attached to this message.

GN :)

![fb error](https://user-images.githubusercontent.com/13874464/30566183-43c201b6-9ccb-11e7-8a9c-dbb68bd211a3.jpg)
![festify error](https://user-images.githubusercontent.com/13874464/30566185-45ecbca6-9ccb-11e7-99bc-e7cb85974a1f.jpg)

**Comment by PrinceNebulon** [comment]
This also happens for me. I don't see the cookies error, but after authenticating with facebook, the auth window just sits there and won't close. The app is entirely unusable because of this. It's broken in the same way on both windows and mac.

**Comment by leolabs** [comment]
This is a weird case. We're on it and will update the ticket as soon as we have a proper solution.

**Comment by leolabs** [comment]
Fixed with version 0.2.10

**Comment by tilmanpotthof** [comment]
@leolabs I just downloaded the app for Mac OS (Version 0.2.10) an I get the same bug.

Isn't it possible to redirect to the default browser of the system, like the Spotify app. This would solve the issue and would have the advantage that I don't need to login, if I'm already authenticated in my default browser.

**Comment by leolabs** [comment]
Hey @tilmanpotthof,
we've completely rewritten Festify from the ground up to make it work in the browser without the need to download anything. Login via Facebook is fixed aswell :)

You can check it out at http://beta.festify.us
