### ISSUE TITLE
Player initialization issues

### ISSUE THREAD

**Issue by tjcahill** [Festify/app#91]
When I try to play from Mac, I get the error "Could not toggle play/pause: Missing Player State", with no other errors. Have reinstalled Spotify and Festify each, done all type of opening one then the other, and Spotify is set to be opened from the web.

macOS Sierra (10.12.6)
Fesitify v. 0.2.8

**Comment by MrLongbottom** [comment]
I have the same problem on windows on my windows computer.

**Comment by Noriso** [comment]
I have the same issue, also tried it on two different computers with no luck. Maybe this issue is related to Spotify updating their Oauth login?

**Comment by MrLongbottom** [comment]
I did some testing, and for some reason it works after I clicked the play button about 20 times. However sometimes it fires up spotify with only one song in queue and therefore doesn't change songs correctly.

**Comment by tjcahill** [comment]
Tried spamming the button, no luck.

Two different computers (Sierra and High Sierra), same issue.

**Comment by bxbroze** [comment]
Hi, Thanks for this amazing app!
Same issue here with windows10. I tried Festify 0.2.8 and 0.2.6.
Spotify version is 1.0.65.320.gac7a8e02.

**Comment by kierr** [comment]
I have the same issue. The Beta mobile app is also erroring. It seems Spotify updated something, and Festify is completely broken.

**Comment by mraerino** [comment]
Seems to be connected to the OAuth flow. Let's investigate that @NeoLegends 
Thanks for your patience, people.

**Comment by lappalal** [comment]
I got it to work with Festify 0.2.6
0.2.8 has the same bug for me on Mac OSX High Sierra

**Comment by gw1503** [comment]
Same problem for me. Any hint waht to do?. Thanks for your help

**Comment by leolabs** [comment]
This problem should be fixed with the latest update. Party on! 😊
