### ISSUE TITLE
Can't get authentication to work; Obvious problem with my .env-default?

### ISSUE THREAD

**Issue by kevinmauro92** [Festify/app#96]
Hey I've been trying for 48 hours now and I just can't get authentication to work. I followed the instructions in the cordova-spotify-oauth2 instructions and set up an AWS lambda server for exchange and refresh tokens.  I enabled anonymous users in my firebase app. How does this look for my .env-default? I just want to get this app working

**Comment by kevinmauro92** [comment]
```
DOMAIN="192.168.1.120"
FIREBASE_API_KEY="AIzaSyATEt5f**************"
FIREBASE_AUTH_DOMAIN="XXXXXX.firebaseapp.com"
FIREBASE_DB_URL="https://XXXXXXX.firebaseio.com"
SPOTIFY_CLIENT_ID="edf2c0b3a1yyyyyyyyyyyyy"
SPOTIFY_CLIENT_TOKEN_URL="https://pbmsehlvp4.execute-api.eu-central-1.amazonaws.com/dev/exchange"
SPOTIFY_TOKEN_SWAP_URL="https://pbmsehlvp4.execute-api.eu-central-1.amazonaws.com/dev/exchange"
SPOTIFY_TOKEN_SWAP_PROTOCOL_URL="https://pbmsehlvp4.execute-api.eu-central-1.amazonaws.com/dev/exchange"
SPOTIFY_TOKEN_REFRESH_URL="https://pbmsehlvp4.execute-api.eu-central-1.amazonaws.com/dev/refresh"
SPOTIFY_REDIRECT_URL="festify-spotify://callback"
SPOTIFY_PROTOCOL_REDIRECT_URL="festify-spotify://callback"
```

"pbmsehlvp4" is provided by the AWS lambda server

How do the redirect URLs look?

**Comment by kevinmauro92** [comment]
My error is "authentication token undefined type" error

**Comment by kevinmauro92** [comment]
I am pretty sure that i am connected to firebase, but then loading the spotify login screen is causing the error. I downloaded the Festify app on the google play store but i didnt have that problem. I tried to decompile the Java source code of the Festify app to see what the exact parameters for these values were but everything was in Java and the xml string values were not provided.

**Comment by kevinmauro92** [comment]
Take the API key from the google-services.json struct downloaded from firebase

**Comment by kevinmauro92** [comment]
Still getting error "Received authentication type of invalid error"

**Comment by kevinmauro92** [comment]
I think it might be a problem with the redirectURL? What are people using for this?

**Comment by kevinmauro92** [comment]
When i delete the app data, I can get the spotify login to load. it goes to spotify and i think it passes my token back. but then it goes back to an app loading screen and crashes. so it is probably a problem with the redirect URL?

**Comment by NeoLegends** [comment]
Did you register your redirect URL with Spotify?

**Comment by NeoLegends** [comment]
Closing this for housekeeping purposes. Feel free to reopen or comment on this if you're still facing the issue. :)
